function rateBell = BellRate_from_lists( ...
    LA, LB, sigGKP, etas, etam, etad, etac, Lcavity, ...
    Aidx, Bidx, v, N)

bellErr = BellErrors_from_lists( ...
    LA, LB, sigGKP, etas, etam, etad, etac, Lcavity, ...
    Aidx, Bidx, v, N);

rateBell = BellRate_from_errors(bellErr);

end