function rateGHZ = GHZRate_from_lists( ...
    LA, LB, LC, sigGKP, etas, etam, etad, etac, Lcavity, ...
    Aidx, Bidx, Cidx, v, N)

if isempty(Aidx) || isempty(Bidx) || isempty(Cidx)
    rateGHZ = 0;
    return;
end

ghzPauliOperatorProbabilities = ...
    map_swapping_results_to_pauli_operator_probabilities_from_lists( ...
        LA, LB, LC, ...
        sigGKP, etas, etam, etad, etac, Lcavity, ...
        Aidx, Bidx, Cidx, ...
        v, N);

rateGHZ = GHZRate_from_pauli_probabilities(ghzPauliOperatorProbabilities);

end